//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceDove
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanHangDoveEntities2 : DbContext
    {
        public BanHangDoveEntities2()
            : base("name=BanHangDoveEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<DanhMuc> DanhMuc { get; set; }
        public DbSet<DonHang> DonHang { get; set; }
        public DbSet<NguoiMua> NguoiMua { get; set; }
        public DbSet<PhanHoi> PhanHoi { get; set; }
        public DbSet<SanPham> SanPham { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
